workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    panoraOpenapi-github-main:
        inputs:
            - location: https://raw.githubusercontent.com/panoratech/Panora/main/packages/api/swagger/swagger-spec.json
        registry:
            location: registry.speakeasyapi.dev/panora/panora/panora-openapi-github-main
targets:
    my-first-target:
        target: typescript
        source: panoraOpenapi-github-main
        codeSamples:
            output: codeSamples.yaml
